#!/usr/bin/env python3
"""Reuse the survey's canonical Nam et al. citation key and update its metadata."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OLD_NEW_KEY = "namRealTimeDynamicScenes2021"
CANONICAL_KEY = "nam_real-time_2020"

article = ROOT / "article/2active.tex"
text = article.read_text(encoding="utf-8")
if OLD_NEW_KEY in text:
    text = text.replace(OLD_NEW_KEY, CANONICAL_KEY)
if "full-pipeline real-time NLOS video milestone" not in text:
    raise RuntimeError("Real-time NLOS survey paragraph is missing")
article.write_text(text, encoding="utf-8")

bib = ROOT / "egbib_20260712_realtime_updates.bib"
bib.write_text("""% Final-venue metadata override for the survey's canonical real-time NLOS key.

@article{nam_real-time_2020,
  author = {Nam, Ji Hyun and Brandt, Eric and Bauer, Sebastian and Liu, Xiaochun and Sifakis, Eftychios and Velten, Andreas},
  title = {Real-time Non-line-of-Sight imaging of dynamic scenes},
  journal = {Nature Communications},
  volume = {12},
  pages = {6526},
  year = {2021},
  doi = {10.1038/s41467-021-26721-x},
  url = {https://doi.org/10.1038/s41467-021-26721-x}
}
""", encoding="utf-8")

note = ROOT / "updates/2026-07-12-realtime-dynamic-nlos-citation-tracing-update.md"
note_text = note.read_text(encoding="utf-8")
note_text = note_text.replace(f"`{OLD_NEW_KEY}`", f"`{CANONICAL_KEY}`")
note_text = note_text.replace(
    "- `egbib_merged_20260711.bib`: regenerated by the duplicate-free bibliography merger.",
    "- `egbib_merged_20260711.bib`: regenerated by the duplicate-free bibliography merger; the existing canonical key is reused so the paper appears only once in the compiled references.",
)
note.write_text(note_text, encoding="utf-8")

print("Reused canonical real-time NLOS citation key and removed duplicate metadata")
