#!/usr/bin/env python3
"""Reuse the canonical Nam et al. key and synchronize final publisher metadata."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OLD_KEY = "namRealTimeDynamicScenes2021"
CANONICAL_KEY = "nam_real-time_2020"
PREPRINT_TITLE = "Real-time Non-line-of-Sight imaging of dynamic scenes"
FINAL_TITLE = "Low-latency time-of-flight non-line-of-sight imaging at 5 frames per second"

# Public-facing artifacts must use the final Nature Communications title rather
# than combining the preprint title with the journal venue.
for rel in ("README.md", "index.html"):
    path = ROOT / rel
    text = path.read_text(encoding="utf-8")
    text = text.replace(PREPRINT_TITLE, FINAL_TITLE)
    path.write_text(text, encoding="utf-8")

article = ROOT / "article/2active.tex"
text = article.read_text(encoding="utf-8")
if OLD_KEY in text:
    text = text.replace(OLD_KEY, CANONICAL_KEY)
if "full-pipeline real-time NLOS video milestone" not in text:
    raise RuntimeError("Real-time NLOS survey paragraph is missing")
article.write_text(text, encoding="utf-8")

# Final publisher metadata. The journal article adds Marco Renna and Alberto
# Tosi relative to the early arXiv author list and has a different final title.
bib = ROOT / "egbib_20260712_realtime_updates.bib"
bib.write_text("""% Final-venue metadata override for the survey's canonical real-time NLOS key.

@article{nam_real-time_2020,
  author = {Nam, Ji Hyun and Brandt, Eric and Bauer, Sebastian and Liu, Xiaochun and Renna, Marco and Tosi, Alberto and Sifakis, Eftychios and Velten, Andreas},
  title = {Low-latency time-of-flight non-line-of-sight imaging at 5 frames per second},
  journal = {Nature Communications},
  volume = {12},
  pages = {6526},
  year = {2021},
  doi = {10.1038/s41467-021-26721-x},
  url = {https://doi.org/10.1038/s41467-021-26721-x}
}
""", encoding="utf-8")

note = ROOT / "updates/2026-07-12-realtime-dynamic-nlos-citation-tracing-update.md"
note_text = note.read_text(encoding="utf-8")
note_text = note_text.replace(PREPRINT_TITLE, FINAL_TITLE)
note_text = note_text.replace(f"`{OLD_KEY}`", f"`{CANONICAL_KEY}`")
note_text = note_text.replace(
    "The final publication is **Nature Communications 12, 6526 (2021)**, DOI `10.1038/s41467-021-26721-x`; it is therefore labeled by the journal rather than by its 2020 arXiv preprint.",
    "The final publication is **Low-latency time-of-flight non-line-of-sight imaging at 5 frames per second**, Nature Communications 12, 6526 (2021), DOI `10.1038/s41467-021-26721-x`. The repository therefore uses the publisher title, full eight-author list, and journal venue rather than the shorter 2020 arXiv metadata.",
)
note_text = note_text.replace(
    "- `egbib_merged_20260711.bib`: regenerated by the duplicate-free bibliography merger.",
    "- `egbib_merged_20260711.bib`: regenerated by the duplicate-free bibliography merger; the existing canonical key is reused so the paper appears only once in the compiled references.",
)
note.write_text(note_text, encoding="utf-8")

for rel in ("README.md", "index.html"):
    text = (ROOT / rel).read_text(encoding="utf-8")
    if FINAL_TITLE not in text or PREPRINT_TITLE in text:
        raise RuntimeError(f"Final-title synchronization failed for {rel}")

print("Synchronized canonical key and final Nature Communications metadata")
