#!/usr/bin/env python3
"""Create one duplicate-free bibliography for the NLOS survey.

The repository accumulated chronological supplemental BibTeX files. Passing all
of them directly to BibTeX is unsafe because several correction files repeat
keys from the base bibliography or earlier supplements. This script parses the
entries, applies an explicit source priority (base, broad 2026 supplement, then
chronological dated supplements), keeps the highest-priority version of every
key, writes a consolidated bibliography, and points ``bare_jrnl.tex`` to it.

The parser is deliberately brace-aware and aborts on malformed entries rather
than silently truncating a bibliography file.
"""
from __future__ import annotations

from collections import OrderedDict
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "egbib_merged_20260711.bib"
NOTE = ROOT / "updates/2026-07-11-bibliography-deduplication.md"


def source_files() -> list[Path]:
    all_files = [p for p in ROOT.glob("egbib*.bib") if p.name != OUTPUT.name]
    base = ROOT / "egbib.bib"
    broad = ROOT / "egbib_2026_updates.bib"
    ordered: list[Path] = []
    for preferred in (base, broad):
        if preferred in all_files:
            ordered.append(preferred)
    ordered.extend(sorted(p for p in all_files if p not in ordered))
    if not ordered:
        raise RuntimeError("No egbib*.bib sources were found")
    return ordered


def parse_entries(path: Path) -> list[tuple[str, str]]:
    text = path.read_text(encoding="utf-8-sig")
    entries: list[tuple[str, str]] = []
    cursor = 0
    while True:
        start = text.find("@", cursor)
        if start < 0:
            break

        type_match = re.match(r"@\s*([A-Za-z]+)\s*([\{(])", text[start:])
        if not type_match:
            cursor = start + 1
            continue

        entry_type = type_match.group(1).lower()
        opener = type_match.group(2)
        closer = "}" if opener == "{" else ")"
        open_pos = start + type_match.end() - 1
        depth = 0
        in_quote = False
        escaped = False
        end: int | None = None

        for i in range(open_pos, len(text)):
            ch = text[i]
            if escaped:
                escaped = False
                continue
            if ch == "\\":
                escaped = True
                continue
            if ch == '"':
                in_quote = not in_quote
                continue
            if in_quote:
                continue
            if ch == opener:
                depth += 1
            elif ch == closer:
                depth -= 1
                if depth == 0:
                    end = i + 1
                    break

        if end is None:
            raise RuntimeError(f"Malformed BibTeX entry in {path.name} near byte {start}")

        raw = text[start:end].strip()
        inside = text[open_pos + 1:end - 1]
        if entry_type in {"string", "preamble", "comment"}:
            key = f"__{entry_type}_{path.name}_{start}"
        else:
            comma = inside.find(",")
            if comma < 0:
                raise RuntimeError(f"BibTeX entry without key delimiter in {path.name}: {raw[:100]}")
            key = inside[:comma].strip()
            if not key:
                raise RuntimeError(f"Empty BibTeX key in {path.name}: {raw[:100]}")
        entries.append((key, raw))
        cursor = end
    return entries


def main() -> None:
    sources = source_files()
    merged: OrderedDict[str, tuple[str, str]] = OrderedDict()
    replacements: list[tuple[str, str, str]] = []

    for source in sources:
        for key, raw in parse_entries(source):
            if key in merged:
                previous_source = merged[key][0]
                replacements.append((key, previous_source, source.name))
                del merged[key]
            merged[key] = (source.name, raw)

    header = [
        "% Auto-generated duplicate-free bibliography for bare_jrnl.tex.",
        "% Generated by scripts/merge_nlos_bibliography.py.",
        "% Source priority: base bibliography, broad 2026 supplement, then dated supplements.",
        "",
    ]
    body = "\n\n".join(raw for _source, raw in merged.values())
    OUTPUT.write_text("\n".join(header) + body + "\n", encoding="utf-8")

    tex_path = ROOT / "bare_jrnl.tex"
    tex = tex_path.read_text(encoding="utf-8")
    pattern = re.compile(r"(?m)^\\bibliography\{[^}]+\}\s*$")
    matches = pattern.findall(tex)
    if len(matches) != 1:
        raise RuntimeError(f"Expected exactly one active bibliography command, found {len(matches)}")
    tex = pattern.sub(r"\\bibliography{egbib_merged_20260711}", tex, count=1)
    tex_path.write_text(tex, encoding="utf-8")

    duplicate_lines = "\n".join(
        f"- `{key}`: `{old}` → `{new}`" for key, old, new in replacements
    ) or "- None."
    note = f"""# 11 July 2026 bibliography deduplication

The survey previously passed every chronological `egbib*.bib` supplement directly to BibTeX. Several supplements intentionally repeated keys to correct venue or metadata, which caused BibTeX to stop with repeated-entry errors before producing `bare_jrnl.bbl`.

This update generates `egbib_merged_20260711.bib` from {len(sources)} source files and keeps one highest-priority record for each of {len(merged)} unique keys. Priority is deterministic: `egbib.bib`, then `egbib_2026_updates.bib`, followed by dated supplements in chronological filename order, so later corrections override older records. `bare_jrnl.tex` now uses only the consolidated bibliography.

## Duplicate keys resolved

{duplicate_lines}

The CI workflow performs a clean LaTeX/BibTeX build, rejects undefined citations or repeated entries, validates the PDF with `pdfinfo` and `pdftotext`, and verifies that the newly integrated X-band radar and Neural Illumination Fields records appear in the generated bibliography.
"""
    NOTE.parent.mkdir(parents=True, exist_ok=True)
    NOTE.write_text(note, encoding="utf-8")

    print(
        f"Merged {sum(len(parse_entries(p)) for p in sources)} records from "
        f"{len(sources)} sources into {len(merged)} unique entries; "
        f"resolved {len(replacements)} duplicate keys."
    )


if __name__ == "__main__":
    main()
