#!/usr/bin/env python3
"""Create one duplicate-free bibliography for the NLOS survey.

The repository accumulated chronological supplemental BibTeX files. Passing all
of them directly to BibTeX is unsafe because several correction files repeat
keys from the base bibliography or earlier supplements. This script parses each
source with ``bibtexparser``, applies an explicit source priority (base, broad
2026 supplement, then chronological dated supplements), keeps the
highest-priority version of every key, writes a consolidated bibliography, and
points ``bare_jrnl.tex`` to it.
"""
from __future__ import annotations

from collections import OrderedDict
from pathlib import Path
import re

import bibtexparser
from bibtexparser.bibdatabase import BibDatabase
from bibtexparser.bparser import BibTexParser
from bibtexparser.bwriter import BibTexWriter

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "egbib_merged_20260711.bib"
NOTE = ROOT / "updates/2026-07-11-bibliography-deduplication.md"


def source_files() -> list[Path]:
    all_files = [p for p in ROOT.glob("egbib*.bib") if p.name != OUTPUT.name]
    base = ROOT / "egbib.bib"
    broad = ROOT / "egbib_2026_updates.bib"
    ordered: list[Path] = []
    for preferred in (base, broad):
        if preferred in all_files:
            ordered.append(preferred)
    ordered.extend(sorted(p for p in all_files if p not in ordered))
    if not ordered:
        raise RuntimeError("No egbib*.bib sources were found")
    return ordered


def load_entries(path: Path) -> list[dict[str, str]]:
    parser = BibTexParser(common_strings=True)
    parser.ignore_nonstandard_types = False
    with path.open("r", encoding="utf-8-sig") as handle:
        database = bibtexparser.load(handle, parser=parser)
    if not database.entries:
        raise RuntimeError(f"No BibTeX entries parsed from {path.name}")
    return database.entries


def main() -> None:
    sources = source_files()
    merged: OrderedDict[str, tuple[str, dict[str, str]]] = OrderedDict()
    replacements: list[tuple[str, str, str]] = []
    parsed_total = 0

    for source in sources:
        entries = load_entries(source)
        parsed_total += len(entries)
        for entry in entries:
            key = entry.get("ID", "").strip()
            if not key:
                raise RuntimeError(f"Parsed entry without ID in {source.name}")
            if key in merged:
                previous_source = merged[key][0]
                replacements.append((key, previous_source, source.name))
                del merged[key]
            merged[key] = (source.name, entry)

    database = BibDatabase()
    database.entries = [entry for _source, entry in merged.values()]
    writer = BibTexWriter()
    writer.indent = "  "
    writer.order_entries_by = None
    rendered = writer.write(database)
    header = (
        "% Auto-generated duplicate-free bibliography for bare_jrnl.tex.\n"
        "% Generated by scripts/merge_nlos_bibliography.py.\n"
        "% Source priority: base bibliography, broad 2026 supplement, then dated supplements.\n\n"
    )
    OUTPUT.write_text(header + rendered, encoding="utf-8")

    tex_path = ROOT / "bare_jrnl.tex"
    tex = tex_path.read_text(encoding="utf-8")
    pattern = re.compile(r"(?m)^\\bibliography\{[^}]+\}\s*$")
    matches = pattern.findall(tex)
    if len(matches) != 1:
        raise RuntimeError(f"Expected exactly one active bibliography command, found {len(matches)}")
    tex = pattern.sub(lambda _m: r"\bibliography{egbib_merged_20260711}", tex, count=1)
    tex_path.write_text(tex, encoding="utf-8")

    duplicate_lines = "\n".join(
        f"- `{key}`: `{old}` → `{new}`" for key, old, new in replacements
    ) or "- None."
    note = f"""# 11 July 2026 bibliography deduplication

The survey previously passed every chronological `egbib*.bib` supplement directly to BibTeX. Several supplements intentionally repeated keys to correct venue or metadata, which caused BibTeX to stop with repeated-entry errors before producing `bare_jrnl.bbl`.

This update generates `egbib_merged_20260711.bib` from {len(sources)} source files and keeps one highest-priority record for each of {len(merged)} unique keys. Priority is deterministic: `egbib.bib`, then `egbib_2026_updates.bib`, followed by dated supplements in chronological filename order, so later corrections override older records. `bare_jrnl.tex` now uses only the consolidated bibliography.

## Duplicate keys resolved

{duplicate_lines}

The CI workflow performs a clean LaTeX/BibTeX build, rejects undefined citations or repeated entries, validates the PDF with `pdfinfo` and `pdftotext`, and verifies that the newly integrated X-band radar and Neural Illumination Fields records appear in the generated bibliography.
"""
    NOTE.parent.mkdir(parents=True, exist_ok=True)
    NOTE.write_text(note, encoding="utf-8")

    print(
        f"Merged {parsed_total} parsed records from {len(sources)} sources into "
        f"{len(merged)} unique entries; resolved {len(replacements)} duplicate keys."
    )


if __name__ == "__main__":
    main()
